/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedValidacaoRouteImport } from './routes/_authenticated/validacao'
import { Route as AuthenticatedPublicacaoRouteImport } from './routes/_authenticated/publicacao'
import { Route as AuthenticatedPrognosticosRouteImport } from './routes/_authenticated/prognosticos'
import { Route as AuthenticatedImportarRouteImport } from './routes/_authenticated/importar'
import { Route as AuthenticatedHistoricoRouteImport } from './routes/_authenticated/historico'
import { Route as AuthenticatedEstatisticasRouteImport } from './routes/_authenticated/estatisticas'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedBankrollRouteImport } from './routes/_authenticated/bankroll'

const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/_authenticated/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedValidacaoRoute = AuthenticatedValidacaoRouteImport.update({
  id: '/_authenticated/validacao',
  path: '/validacao',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPublicacaoRoute = AuthenticatedPublicacaoRouteImport.update({
  id: '/_authenticated/publicacao',
  path: '/publicacao',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPrognosticosRoute =
  AuthenticatedPrognosticosRouteImport.update({
    id: '/_authenticated/prognosticos',
    path: '/prognosticos',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedImportarRoute = AuthenticatedImportarRouteImport.update({
  id: '/_authenticated/importar',
  path: '/importar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedHistoricoRoute = AuthenticatedHistoricoRouteImport.update({
  id: '/_authenticated/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedEstatisticasRoute =
  AuthenticatedEstatisticasRouteImport.update({
    id: '/_authenticated/estatisticas',
    path: '/estatisticas',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/_authenticated/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedBankrollRoute = AuthenticatedBankrollRouteImport.update({
  id: '/_authenticated/bankroll',
  path: '/bankroll',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/bankroll': typeof AuthenticatedBankrollRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/estatisticas': typeof AuthenticatedEstatisticasRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/importar': typeof AuthenticatedImportarRoute
  '/prognosticos': typeof AuthenticatedPrognosticosRoute
  '/publicacao': typeof AuthenticatedPublicacaoRoute
  '/validacao': typeof AuthenticatedValidacaoRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesByTo {
  '/bankroll': typeof AuthenticatedBankrollRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/estatisticas': typeof AuthenticatedEstatisticasRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/importar': typeof AuthenticatedImportarRoute
  '/prognosticos': typeof AuthenticatedPrognosticosRoute
  '/publicacao': typeof AuthenticatedPublicacaoRoute
  '/validacao': typeof AuthenticatedValidacaoRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated/bankroll': typeof AuthenticatedBankrollRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/estatisticas': typeof AuthenticatedEstatisticasRoute
  '/_authenticated/historico': typeof AuthenticatedHistoricoRoute
  '/_authenticated/importar': typeof AuthenticatedImportarRoute
  '/_authenticated/prognosticos': typeof AuthenticatedPrognosticosRoute
  '/_authenticated/publicacao': typeof AuthenticatedPublicacaoRoute
  '/_authenticated/validacao': typeof AuthenticatedValidacaoRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/bankroll'
    | '/configuracoes'
    | '/estatisticas'
    | '/historico'
    | '/importar'
    | '/prognosticos'
    | '/publicacao'
    | '/validacao'
    | '/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/bankroll'
    | '/configuracoes'
    | '/estatisticas'
    | '/historico'
    | '/importar'
    | '/prognosticos'
    | '/publicacao'
    | '/validacao'
    | '/'
  id:
    | '__root__'
    | '/_authenticated/bankroll'
    | '/_authenticated/configuracoes'
    | '/_authenticated/estatisticas'
    | '/_authenticated/historico'
    | '/_authenticated/importar'
    | '/_authenticated/prognosticos'
    | '/_authenticated/publicacao'
    | '/_authenticated/validacao'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedBankrollRoute: typeof AuthenticatedBankrollRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedEstatisticasRoute: typeof AuthenticatedEstatisticasRoute
  AuthenticatedHistoricoRoute: typeof AuthenticatedHistoricoRoute
  AuthenticatedImportarRoute: typeof AuthenticatedImportarRoute
  AuthenticatedPrognosticosRoute: typeof AuthenticatedPrognosticosRoute
  AuthenticatedPublicacaoRoute: typeof AuthenticatedPublicacaoRoute
  AuthenticatedValidacaoRoute: typeof AuthenticatedValidacaoRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/validacao': {
      id: '/_authenticated/validacao'
      path: '/validacao'
      fullPath: '/validacao'
      preLoaderRoute: typeof AuthenticatedValidacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/publicacao': {
      id: '/_authenticated/publicacao'
      path: '/publicacao'
      fullPath: '/publicacao'
      preLoaderRoute: typeof AuthenticatedPublicacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/prognosticos': {
      id: '/_authenticated/prognosticos'
      path: '/prognosticos'
      fullPath: '/prognosticos'
      preLoaderRoute: typeof AuthenticatedPrognosticosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/importar': {
      id: '/_authenticated/importar'
      path: '/importar'
      fullPath: '/importar'
      preLoaderRoute: typeof AuthenticatedImportarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/historico': {
      id: '/_authenticated/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof AuthenticatedHistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/estatisticas': {
      id: '/_authenticated/estatisticas'
      path: '/estatisticas'
      fullPath: '/estatisticas'
      preLoaderRoute: typeof AuthenticatedEstatisticasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/bankroll': {
      id: '/_authenticated/bankroll'
      path: '/bankroll'
      fullPath: '/bankroll'
      preLoaderRoute: typeof AuthenticatedBankrollRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedBankrollRoute: AuthenticatedBankrollRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedEstatisticasRoute: AuthenticatedEstatisticasRoute,
  AuthenticatedHistoricoRoute: AuthenticatedHistoricoRoute,
  AuthenticatedImportarRoute: AuthenticatedImportarRoute,
  AuthenticatedPrognosticosRoute: AuthenticatedPrognosticosRoute,
  AuthenticatedPublicacaoRoute: AuthenticatedPublicacaoRoute,
  AuthenticatedValidacaoRoute: AuthenticatedValidacaoRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
