/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedValidacaoRouteImport } from './routes/_authenticated/validacao'
import { Route as AuthenticatedPublicacaoRouteImport } from './routes/_authenticated/publicacao'
import { Route as AuthenticatedPrognosticosRouteImport } from './routes/_authenticated/prognosticos'
import { Route as AuthenticatedModelosPreditivosRouteImport } from './routes/_authenticated/modelos-preditivos'
import { Route as AuthenticatedImportarRouteImport } from './routes/_authenticated/importar'
import { Route as AuthenticatedHistoricoRouteImport } from './routes/_authenticated/historico'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedColetaDadosRouteImport } from './routes/_authenticated/coleta-dados'
import { Route as AuthenticatedBaseDadosRouteImport } from './routes/_authenticated/base-dados'
import { Route as AuthenticatedBankrollRouteImport } from './routes/_authenticated/bankroll'
import { Route as AuthenticatedAprendizadoIaRouteImport } from './routes/_authenticated/aprendizado-ia'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as ApiPublicHooksSyncCriticalValidationTelegramAlertsRouteImport } from './routes/api/public/hooks/sync-critical-validation-telegram-alerts'
import { Route as ApiPublicHooksSendCriticalValidationTelegramAlertsRouteImport } from './routes/api/public/hooks/send-critical-validation-telegram-alerts'

const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedValidacaoRoute = AuthenticatedValidacaoRouteImport.update({
  id: '/validacao',
  path: '/validacao',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPublicacaoRoute = AuthenticatedPublicacaoRouteImport.update({
  id: '/publicacao',
  path: '/publicacao',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPrognosticosRoute =
  AuthenticatedPrognosticosRouteImport.update({
    id: '/prognosticos',
    path: '/prognosticos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedModelosPreditivosRoute =
  AuthenticatedModelosPreditivosRouteImport.update({
    id: '/modelos-preditivos',
    path: '/modelos-preditivos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedImportarRoute = AuthenticatedImportarRouteImport.update({
  id: '/importar',
  path: '/importar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoricoRoute = AuthenticatedHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedColetaDadosRoute =
  AuthenticatedColetaDadosRouteImport.update({
    id: '/coleta-dados',
    path: '/coleta-dados',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBaseDadosRoute = AuthenticatedBaseDadosRouteImport.update({
  id: '/base-dados',
  path: '/base-dados',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBankrollRoute = AuthenticatedBankrollRouteImport.update({
  id: '/bankroll',
  path: '/bankroll',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAprendizadoIaRoute =
  AuthenticatedAprendizadoIaRouteImport.update({
    id: '/aprendizado-ia',
    path: '/aprendizado-ia',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksSyncCriticalValidationTelegramAlertsRoute =
  ApiPublicHooksSyncCriticalValidationTelegramAlertsRouteImport.update({
    id: '/api/public/hooks/sync-critical-validation-telegram-alerts',
    path: '/api/public/hooks/sync-critical-validation-telegram-alerts',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSendCriticalValidationTelegramAlertsRoute =
  ApiPublicHooksSendCriticalValidationTelegramAlertsRouteImport.update({
    id: '/api/public/hooks/send-critical-validation-telegram-alerts',
    path: '/api/public/hooks/send-critical-validation-telegram-alerts',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/aprendizado-ia': typeof AuthenticatedAprendizadoIaRoute
  '/bankroll': typeof AuthenticatedBankrollRoute
  '/base-dados': typeof AuthenticatedBaseDadosRoute
  '/coleta-dados': typeof AuthenticatedColetaDadosRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/importar': typeof AuthenticatedImportarRoute
  '/modelos-preditivos': typeof AuthenticatedModelosPreditivosRoute
  '/prognosticos': typeof AuthenticatedPrognosticosRoute
  '/publicacao': typeof AuthenticatedPublicacaoRoute
  '/validacao': typeof AuthenticatedValidacaoRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/hooks/send-critical-validation-telegram-alerts': typeof ApiPublicHooksSendCriticalValidationTelegramAlertsRoute
  '/api/public/hooks/sync-critical-validation-telegram-alerts': typeof ApiPublicHooksSyncCriticalValidationTelegramAlertsRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/aprendizado-ia': typeof AuthenticatedAprendizadoIaRoute
  '/bankroll': typeof AuthenticatedBankrollRoute
  '/base-dados': typeof AuthenticatedBaseDadosRoute
  '/coleta-dados': typeof AuthenticatedColetaDadosRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/importar': typeof AuthenticatedImportarRoute
  '/modelos-preditivos': typeof AuthenticatedModelosPreditivosRoute
  '/prognosticos': typeof AuthenticatedPrognosticosRoute
  '/publicacao': typeof AuthenticatedPublicacaoRoute
  '/validacao': typeof AuthenticatedValidacaoRoute
  '/': typeof AuthenticatedIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/hooks/send-critical-validation-telegram-alerts': typeof ApiPublicHooksSendCriticalValidationTelegramAlertsRoute
  '/api/public/hooks/sync-critical-validation-telegram-alerts': typeof ApiPublicHooksSyncCriticalValidationTelegramAlertsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/aprendizado-ia': typeof AuthenticatedAprendizadoIaRoute
  '/_authenticated/bankroll': typeof AuthenticatedBankrollRoute
  '/_authenticated/base-dados': typeof AuthenticatedBaseDadosRoute
  '/_authenticated/coleta-dados': typeof AuthenticatedColetaDadosRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/historico': typeof AuthenticatedHistoricoRoute
  '/_authenticated/importar': typeof AuthenticatedImportarRoute
  '/_authenticated/modelos-preditivos': typeof AuthenticatedModelosPreditivosRoute
  '/_authenticated/prognosticos': typeof AuthenticatedPrognosticosRoute
  '/_authenticated/publicacao': typeof AuthenticatedPublicacaoRoute
  '/_authenticated/validacao': typeof AuthenticatedValidacaoRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/hooks/send-critical-validation-telegram-alerts': typeof ApiPublicHooksSendCriticalValidationTelegramAlertsRoute
  '/api/public/hooks/sync-critical-validation-telegram-alerts': typeof ApiPublicHooksSyncCriticalValidationTelegramAlertsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/aprendizado-ia'
    | '/bankroll'
    | '/base-dados'
    | '/coleta-dados'
    | '/configuracoes'
    | '/historico'
    | '/importar'
    | '/modelos-preditivos'
    | '/prognosticos'
    | '/publicacao'
    | '/validacao'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/hooks/send-critical-validation-telegram-alerts'
    | '/api/public/hooks/sync-critical-validation-telegram-alerts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/aprendizado-ia'
    | '/bankroll'
    | '/base-dados'
    | '/coleta-dados'
    | '/configuracoes'
    | '/historico'
    | '/importar'
    | '/modelos-preditivos'
    | '/prognosticos'
    | '/publicacao'
    | '/validacao'
    | '/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/hooks/send-critical-validation-telegram-alerts'
    | '/api/public/hooks/sync-critical-validation-telegram-alerts'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/aprendizado-ia'
    | '/_authenticated/bankroll'
    | '/_authenticated/base-dados'
    | '/_authenticated/coleta-dados'
    | '/_authenticated/configuracoes'
    | '/_authenticated/historico'
    | '/_authenticated/importar'
    | '/_authenticated/modelos-preditivos'
    | '/_authenticated/prognosticos'
    | '/_authenticated/publicacao'
    | '/_authenticated/validacao'
    | '/_authenticated/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/hooks/send-critical-validation-telegram-alerts'
    | '/api/public/hooks/sync-critical-validation-telegram-alerts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  McpRoute: typeof McpRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicHooksSendCriticalValidationTelegramAlertsRoute: typeof ApiPublicHooksSendCriticalValidationTelegramAlertsRoute
  ApiPublicHooksSyncCriticalValidationTelegramAlertsRoute: typeof ApiPublicHooksSyncCriticalValidationTelegramAlertsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/validacao': {
      id: '/_authenticated/validacao'
      path: '/validacao'
      fullPath: '/validacao'
      preLoaderRoute: typeof AuthenticatedValidacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/publicacao': {
      id: '/_authenticated/publicacao'
      path: '/publicacao'
      fullPath: '/publicacao'
      preLoaderRoute: typeof AuthenticatedPublicacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/prognosticos': {
      id: '/_authenticated/prognosticos'
      path: '/prognosticos'
      fullPath: '/prognosticos'
      preLoaderRoute: typeof AuthenticatedPrognosticosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/modelos-preditivos': {
      id: '/_authenticated/modelos-preditivos'
      path: '/modelos-preditivos'
      fullPath: '/modelos-preditivos'
      preLoaderRoute: typeof AuthenticatedModelosPreditivosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/importar': {
      id: '/_authenticated/importar'
      path: '/importar'
      fullPath: '/importar'
      preLoaderRoute: typeof AuthenticatedImportarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/historico': {
      id: '/_authenticated/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof AuthenticatedHistoricoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/coleta-dados': {
      id: '/_authenticated/coleta-dados'
      path: '/coleta-dados'
      fullPath: '/coleta-dados'
      preLoaderRoute: typeof AuthenticatedColetaDadosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/base-dados': {
      id: '/_authenticated/base-dados'
      path: '/base-dados'
      fullPath: '/base-dados'
      preLoaderRoute: typeof AuthenticatedBaseDadosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bankroll': {
      id: '/_authenticated/bankroll'
      path: '/bankroll'
      fullPath: '/bankroll'
      preLoaderRoute: typeof AuthenticatedBankrollRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/aprendizado-ia': {
      id: '/_authenticated/aprendizado-ia'
      path: '/aprendizado-ia'
      fullPath: '/aprendizado-ia'
      preLoaderRoute: typeof AuthenticatedAprendizadoIaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sync-critical-validation-telegram-alerts': {
      id: '/api/public/hooks/sync-critical-validation-telegram-alerts'
      path: '/api/public/hooks/sync-critical-validation-telegram-alerts'
      fullPath: '/api/public/hooks/sync-critical-validation-telegram-alerts'
      preLoaderRoute: typeof ApiPublicHooksSyncCriticalValidationTelegramAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/send-critical-validation-telegram-alerts': {
      id: '/api/public/hooks/send-critical-validation-telegram-alerts'
      path: '/api/public/hooks/send-critical-validation-telegram-alerts'
      fullPath: '/api/public/hooks/send-critical-validation-telegram-alerts'
      preLoaderRoute: typeof ApiPublicHooksSendCriticalValidationTelegramAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAprendizadoIaRoute: typeof AuthenticatedAprendizadoIaRoute
  AuthenticatedBankrollRoute: typeof AuthenticatedBankrollRoute
  AuthenticatedBaseDadosRoute: typeof AuthenticatedBaseDadosRoute
  AuthenticatedColetaDadosRoute: typeof AuthenticatedColetaDadosRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedHistoricoRoute: typeof AuthenticatedHistoricoRoute
  AuthenticatedImportarRoute: typeof AuthenticatedImportarRoute
  AuthenticatedModelosPreditivosRoute: typeof AuthenticatedModelosPreditivosRoute
  AuthenticatedPrognosticosRoute: typeof AuthenticatedPrognosticosRoute
  AuthenticatedPublicacaoRoute: typeof AuthenticatedPublicacaoRoute
  AuthenticatedValidacaoRoute: typeof AuthenticatedValidacaoRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAprendizadoIaRoute: AuthenticatedAprendizadoIaRoute,
  AuthenticatedBankrollRoute: AuthenticatedBankrollRoute,
  AuthenticatedBaseDadosRoute: AuthenticatedBaseDadosRoute,
  AuthenticatedColetaDadosRoute: AuthenticatedColetaDadosRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedHistoricoRoute: AuthenticatedHistoricoRoute,
  AuthenticatedImportarRoute: AuthenticatedImportarRoute,
  AuthenticatedModelosPreditivosRoute: AuthenticatedModelosPreditivosRoute,
  AuthenticatedPrognosticosRoute: AuthenticatedPrognosticosRoute,
  AuthenticatedPublicacaoRoute: AuthenticatedPublicacaoRoute,
  AuthenticatedValidacaoRoute: AuthenticatedValidacaoRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  McpRoute: McpRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicHooksSendCriticalValidationTelegramAlertsRoute:
    ApiPublicHooksSendCriticalValidationTelegramAlertsRoute,
  ApiPublicHooksSyncCriticalValidationTelegramAlertsRoute:
    ApiPublicHooksSyncCriticalValidationTelegramAlertsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
